version: "3.1"

services:
  backend:
    command: ["main:app", "--reload", "--host", "0.0.0.0"]
    image: "ting2020"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - 8000:8000
    volumes:
    - ./:/app
